

// Async function
const myFunction = async () => {
  try {

  } catch(error) {
    console.error(error);
  }
}
